server:
  servlet:
    context-path: /api/v1
  port: 8081

management:
  server:
    port: 9091

spring:
  application:
    name: shop
  main:
    banner-mode: off

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    ru.gurok.shop: INFO
