server:
  servlet:
    context-path: /api/v1
  port: 8081

management:
  server:
    port: 9091

spring:
  application:
    name: shop
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true
  datasource:
    url: jdbc:h2:mem:shopdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: p
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    ru.gurok.shop: INFO
