server:
  servlet:
    context-path: /api/v1
  port: 8080

management:
  server:
    port: 9090

spring:
  application:
    name: shop
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    ru.gurok.shop: INFO
